name: Python Microservice Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t karlisrb/python-greetings-app:latest .
        echo "Pushing Docker image to DockerHub..."
        docker push karlisrb/python-greetings-app:latest

  deploy-to-dev:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to DEV
      run: |
        echo "Deploying Python microservice to DEV environment..."
        docker pull karlisrb/python-greetings-app:latest
        docker-compose down
        docker-compose up -d

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
    - name: Run tests on DEV
      run: |
        echo "Running tests on DEV environment..."
        docker pull karlisrb/api-tests:latest
        docker run --network=host --rm karlisrb/api-tests:latest run greetings greetings_dev

  deploy-to-stg:
    needs: tests-on-dev
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to STG
      run: |
        echo "Deploying Python microservice to STG environment..."
        docker pull karlisrb/python-greetings-app:latest
        docker-compose down
        docker-compose up -d

  tests-on-stg:
    needs: deploy-to-stg
    runs-on: ubuntu-latest
    steps:
    - name: Run tests on STG
      run: |
        echo "Running tests on STG environment..."
        docker pull karlisrb/api-tests:latest
        docker run --network=host --rm karlisrb/api-tests:latest run greetings greetings_stg

  deploy-to-prod:
    needs: tests-on-stg
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to PROD
      run: |
        echo "Deploying Python microservice to PROD environment..."
        docker pull karlisrb/python-greetings-app:latest
        docker-compose down
        docker-compose up -d

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    steps:
    - name: Run tests on PROD
      run: |
        echo "Running tests on PROD environment..."
        docker pull karlisrb/api-tests:latest
        docker run --network=host --rm karlisrb/api-tests:latest run greetings greetings_prod
